<?php

/**
*
* Implements hook_theme()
*/
function ajax_search_block_theme($existing, $type, $theme, $path) {
    return array(
        'block_ajax_search' =>
            array(
                'variables' => array(
                    'block_title' => null,
                ),
                'template' => 'block--block-ajaxsearch',
        )
    );
}

/**
*
* Implements hook_page_attachments_alter()
*/
function ajax_search_block_page_attachments_alter(&$page) {
  $config = \Drupal::config('ajax_search_block.settings');
  $ajax_base_url = (!empty($config->get('ajax_base_url'))) ? $config->get('ajax_base_url') : null;
  $page['#attached']['drupalSettings']['ajax_search_block']['ajax_base_url'] = $ajax_base_url;
}