<?php

/**
 * @file
 * Main code for CKEditor Bootstrap Editor module.
 */

/**
 * Implements hook_ckeditor_plugin().
 */
function ckeditor_bootstrap_editor_ckeditor_plugin() {
  return array(
    'jsplusBootstrapEditor' => array(
      'name' => 'jsplusBootstrapEditor',
      'desc' => t('CKEditor Bootstrap Editor. See <a href=":addon_page_url">@addon_page_title</a> for more details.',
        array(
          ':addon_page_url' => 'http://js.plus/products/bootstrap-editor',
          '@addon_page_title' => t('addon page'),
        )),
      'path' => base_path() . 'libraries/jsplusBootstrapEditor'
    ),
  );
}
