version: "2"

services:
  # mariadb:
  #   image: wodby/mariadb:$MARIADB_TAG
  #   environment:
  #     MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
  #     MYSQL_DATABASE: $DB_NAME
  #     MYSQL_USER: $DB_USER
  #     MYSQL_PASSWORD: $DB_PASSWORD
  #   volumes:
  # #      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
  #    - ./mariadb:/var/lib/mysql # I want to manage volumes manually.


  php:
    image: wodby/drupal-php:$PHP_TAG
    environment:
      # To skip auto init.
      WODBY_APP_NAME: drupal
      DEBUG: 1
      # DRUPAL_VERSION: 8
      # DB_HOST: $DB_HOST
      # DB_NAME: $DB_NAME
      # DB_USER: $DB_USER
      # DB_PASSWORD: $DB_PASSWORD
      # DB_DRIVER: $DB_DRIVER
      PHP_SENDMAIL_PATH: '/bin/true'
    volumes:
      - ./:/var/www/html
      # - codebase:/var/www/html
      # - ./tests:/usr/local/bin/tests
      # - ./test.settings.php:/var/www/html/web/sites/default/test.settings.php
      # - ./varnish-purger.yml:/var/www/html/web/varnish-purger.yml
      # - ./search-api-solr-server.yml:/var/www/html/web/search_api.server.solr_6_4.yml

  nginx:
    image: wodby/drupal-nginx:$NGINX_TAG
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - ./:/var/www/html
    ports:
      - '8989:80'
    depends_on:
      - php

  # varnish:
  #   image: wodby/drupal-varnish:$VARNISH_TAG
  #   depends_on:
  #     - nginx
  #   environment:
  #     VARNISH_SECRET: secret
  #     VARNISH_BACKEND_HOST: nginx
  #     VARNISH_BACKEND_PORT: 80

  # redis:
  #   image: wodby/redis:$REDIS_TAG

  # solr:
  #   image: wodby/drupal-solr:$SOLR_TAG
  #   environment:
  #     SOLR_HEAP: 1024m

volumes:
  codebase:
