<?php

/**
 * @file
 * Main code for CKEditor Bootstrap Widgets module.
 */

/**
 * Implements hook_ckeditor_plugin().
 */
function ckeditor_bootstrap_widgets_ckeditor_plugin() {
  return array(
    'jsplusBootstrapWidgets' => array(
      'name' => 'jsplusBootstrapWidgets',
      'desc' => t('CKEditor Bootstrap Widgets. See <a href=":addon_page_url">@addon_page_title</a> for more details.',
        array(
          ':addon_page_url' => 'http://js.plus/products/bootstrap-widgets',
          '@addon_page_title' => t('addon page'),
        )),
      'path' => base_path() . 'libraries/jsplusBootstrapWidgets'
    ),
  );
}
